#
###################################
# Site wide configuration
####################################
#
title: Jasleen's E-nook
email: jgrewal@bcgsc.ca
description: A simple and awesome blog theme powered by jekyll.
url: https://jasgrewal.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Python", "Jeykyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Canada/Pacific
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

gems:
  - jekyll-last-modified-at
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jasleen Grewal
  avatar: dna3.svg
  job: "PhD Candidate (Bioinformatics) @UBC"
  bio: "Overthinking brown chick prone to getting into arguments on sunny days. Currently working on my PhD in beautiful British Columbia, Canada."
  email: grewalj23@gmail.com
  twitter: jasleen_grewal #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jasgrewal #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
