#
###################################
# Site wide configuration
####################################
#
title: Jasleen Grewal
email: grewalj23@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://jasgrewal.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Python", "Jeykyll", "Jasleen Grewal", "Jasleen Kaur Grewal", "Jasleen cancer research", "UBC"]
google_analytics: UA-119233913-1
#
###################################
# Jekyll configuration
####################################
#
timezone:          Canada/Pacific
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

gems:
  - jekyll-last-modified-at
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jasleen Grewal
  avatar: dna3.svg
  job: "Bioinformatics researcher, PhD"
  bio: "Butter-fingered millennial living out the pandemic in beautiful British Columbia, Canada.<br><br> <b>Looking for</b>  roles in machine learning, precision oncology, or science education."
  descr: "If you are here for Tutorials, please follow [link to repo](https://jasgrewal.github.io/common/)"
  email: grewalj23@gmail.com
  twitter: jasleen_grewal #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-119233913-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jasgrewal #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jasleen-grewal-4336524b
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
